### PR TITLE
added configure maze function file

### PR DESCRIPTION
**Pull request by Junhong-Tan**
function completely coded.

### CODE REVIEW

**Comment by Junhong-Tan** [comment]
@QiaoyingL  function coded, please ask QA to test before merging to the master branch to ensure that the code works

**Comment by ikmaal** [comment]
@MuhammadThaqif 
QA, you can conduct testing for this feature

7731acae5805aa72314609f41c6a89785ec3c8fb

**Comment by Junhong-Tan** [comment]
@QiaoyingL merge and delete the files thanks, realized that the file uploaded was incorrect.

**Comment by QiaoyingL** [comment]
Alright done

**Pull request merged**
